import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MainStoreProvider } from "@/utils/providers/storeProviders";
import ReactQueryProviders from "@/utils/providers/reactQueryProviders";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProviders>
      <html lang='en'>
        <MainStoreProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </MainStoreProvider>
      </html>
    </ReactQueryProviders>
  );
}
